version: "2.1"
services:
  web:
    container_name: rel_list_app
    image: related_listings
    build: ./
    depends_on:
      database:
        condition: service_healthy
    ports: 
      - "80:3001"

  database:
    container_name: localhost
    image: mysql:5.7
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: related_listings
    volumes:
      - ./server/db/Schema.sql:/docker-entrypoint-initdb.d/Schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
    ports:
      - "3307:3306"
