version: "2.1"
services:
  web:
    image: related_listings
    depends_on:
      database:
        condition: service_healthy
    build: ./
    ports: [2000,3001]

  node:
    image: "node:alpine"

  database:
    image: mysql:5.7
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: "Amar"
      MYSQL_DATABASE: related_listings
    volumes:
      - ./Schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 3
    ports:
      - 3003:3003