-- CREATE USER 'amar'@'localhost' IDENTIFIED BY 'password';
-- GRANT ALL PRIVILEGES ON *.* TO 'amar'@'localhost' WITH GRANT OPTION;
-- CREATE USER 'amar'@'%' IDENTIFIED BY 'password';
-- GRANT ALL PRIVILEGES ON *.* TO 'amar'@'%' WITH GRANT OPTION;